robot.name=MeuRobo 1.0
robot.author.name=Turma DS
robot.description=Robo com radar lock, movimento circular e gerenciamento de energia
robot.webpage=
robot.version=1.0
robot.classname=meurobo.MeuRobo
robocode.version=1.11.1
